# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d942dbf21cb757b0ed34ed441a1693a0"
name = "fedex-delivery-status-sync"
application_url = "https://fedex-proxy-lilac.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://fedex-proxy-lilac.vercel.app/api/auth" ]

[app_proxy]
url = "https://fedex-proxy-lilac.vercel.app/proxy/fedex-status"
subpath = "fedex-status"
prefix = "apps"
